import FutureHorizons from "./storage/FutureHorizons";
import Apgc from "./storage/apgc";
import Jpar from "./storage/jpar";

export const projectsData = [
  {  
    id: '1',
    eventImg: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorImg: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorName: "Dillon Chemhere",
    authorTitle: "Associate",
    coAuthorName:"",
    coAuthorTitle:"",
    coAuthorImg: "",
    date: "08 AUGUST 2023",
    title: "Future Horizons: Shaping Tomorrow through Inclusive Research",
    details: `"Future Horizons" is a pioneering research initiative set to commence in January 2024, dedicated to exploring emerging challenges and opportunities that will define our collective future. This program, initiated by the Social and Economic Research Foundation (SERF), will focus on multidisciplinary research encompassing technology, climate, socio-economic trends, healthcare, and education. The initiative aims to provide actionable insights and innovative solutions to navigate the complexities of the evolving world landscape.`,
    storyParagraph1: <FutureHorizons/>,
    storyParagraph2: "This is p2",
    storyParagraph3: "This is P3",
    refesences: "",
    storyParagraph4: "This is P3",
    storyParagraph5: "This is P3",
    storyParagraph6: "This is P3",
  },
  {  
    id: '2',
    eventImg: "https://images.pexels.com/photos/4646833/pexels-photo-4646833.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorImg: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorName: "Dillon Chemhere",
    authorTitle: "Associate",
    coAuthorName:"",
    coAuthorTitle:"",
    coAuthorImg: "",
    date: "08 AUGUST 2023",
    title: "Africa Peace and Governance Consortium",
    details:   `Within the framework of the Social and Economic Research Foundation (SERF), the Africa Peace and Governance Consortium (APGC) emerges as a transformative initiative. Anchored in SERF’s core values of research excellence, APGC is dedicated to promoting peace and championing good governance across Africa, with a particular focus on Kenya and the wider East African region. `,
    storyParagraph1: <Apgc/>,
    storyParagraph2: "This is p2",
    storyParagraph3: "This is P3",
    refesences: "",
    storyParagraph4: "This is P3",
    storyParagraph5: "This is P3",
    storyParagraph6: "This is P3",
  },
  {  
    id: '3',
    eventImg: "https://images.pexels.com/photos/5940708/pexels-photo-5940708.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorImg: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    authorName: "Dillon Chemhere",
    authorTitle: "Associate",
    coAuthorName:"",
    coAuthorTitle:"",
    coAuthorImg: "",
    date: "08 AUGUST 2023",
    title: "The Journal of Professional and Academic Research (JPAR)",
    details:  `The Journal of Professional and Academic Research (JPAR) stands as a prestigious peer-reviewed academic journal, established under the aegis of the Social and Economic Research Foundation (SERF). Our primary objective at JPAR is to elevate the domains of science, knowledge, and practice by fostering the creation and dissemination of top-tier academic research articles and papers. We serve as a vital platform encouraging the development of high-quality scholarly content.`,
    storyParagraph1: <Jpar/>,
    storyParagraph2: "This is p2",
    storyParagraph3: "This is P3",
    refesences: "",
    storyParagraph4: "This is P3",
    storyParagraph5: "This is P3",
    storyParagraph6: "This is P3",
  },
  
  

];
